apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris-container
        image: us-central1-docker.pkg.dev/wise-ally-461615-t2/iris-docker/iris-fastapi:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  selector:
    app: iris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
